services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./backendApi:/var/www/html
    networks:
      - laravel
    ports:
      - 8000:8000
    command: php -S 0.0.0.0:8000 -t public
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - laravel

volumes:
  postgres-data:

networks:
  laravel:
    driver: bridge